# Generated by Django 2.1.7 on 2019-03-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_faculty_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaches',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='f_id',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Teaches',
        ),
    ]
