# Generated by Django 2.1.7 on 2019-03-30 23:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='feedback.Course'),
            preserve_default=False,
        ),
    ]
