# Generated by Django 2.1.7 on 2019-03-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190303_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(default='CSE', max_length=200),
            preserve_default=False,
        ),
    ]
