# Generated by Django 2.1.7 on 2019-03-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_faculty_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='type',
        ),
    ]
