# Generated by Django 2.1.7 on 2019-03-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20190322_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('dept', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Course')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Faculty')),
            ],
        ),
    ]
